return {
  'folke/lazydev.nvim',
  ft = 'lua',
  opts = {
    library = {
      { path = '${3rd}/luv/library', words = { 'vim%.uv' } },
      { path = 'lazy.nvim', words = { 'LazySpec', 'LazyPluginSpec' } },
      { path = 'blink.cmp', words = { 'blink%.cmp' } },
      { path = 'catppuccin', words = { 'Catppuccin', 'Ctp' } },
      { path = 'Comment.nvim', words = { 'CommentConfig' } },
      { path = 'conform.nvim', words = { 'conform%.' } },
      { path = 'easy-dotnet.nvim', words = { 'easy%-dotnet' } },
      { path = 'git-conflict.nvim', words = { 'GitConflict' } },
      { path = 'gitgraph.nvim', words = { 'I%.GGConfig' } },
      { path = 'grug-far.nvim', words = { 'grug%.far' } },
      { path = 'markview.nvim', words = { 'markview%.' } },
      { path = 'noice.nvim', words = { 'Noice' } },
      { path = 'nvim-dap-view', words = { 'dapview', 'dap%-view' } },
      { path = 'nvim-dap-virtual-text', words = { 'nvim_dap_virtual_text' } },
      { path = 'nvim-notify', words = { 'notify%.Config' } },
      { path = 'nvim-treesitter-textobjects', words = { 'TSTextObjects' } },
      { path = 'octo.nvim', words = { 'Octo' } },
      { path = 'oil.nvim', words = { 'oil%.' } },
      { path = 'rainbow-delimiters.nvim', words = { 'rainbow_delimiters' } },
      { path = 'sidekick.nvim', words = { 'sidekick%.' } },
      { path = 'smart-splits.nvim', words = { 'SmartSplits' } },
      { path = 'snacks.nvim', words = { 'Snacks', 'snacks%.' } },
      { path = 'undo-glow.nvim', words = { 'UndoGlow' } },
      { path = 'which-key.nvim', words = { 'wk%.' } },
    },
  },
}
